from __future__ import annotations

import re

_STRIP_BLOCK_TAGS_RE = re.compile(
    r"(?is)<(script|style|iframe|object|embed|link|meta)\b[^>]*>.*?</\1\s*>"
)
_STRIP_VOID_TAGS_RE = re.compile(r"(?is)<(script|style|iframe|object|embed|link|meta)\b[^>]*?/?>")
_REMOVE_EVENT_HANDLER_ATTRS_RE = re.compile(
    r"""(?is)\s+on[a-z0-9_-]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)"""
)
_DANGEROUS_SCHEME_QUOTED_RE = re.compile(
    r"""(?is)\s+(href|src)\s*=\s*(["'])\s*(?:javascript|vbscript|data)\s*:[^"']*\2"""
)
_DANGEROUS_SCHEME_UNQUOTED_RE = re.compile(
    r"""(?is)\s+(href|src)\s*=\s*(?:javascript|vbscript|data)\s*:[^\s>]+"""
)


def sanitize_result_html(value: str) -> str:
    """Sanitize untrusted HTML for admin display.

    This intentionally removes the most common XSS vectors while preserving most
    normal markup generated by commands.
    """
    sanitized = _STRIP_BLOCK_TAGS_RE.sub("", value)
    sanitized = _STRIP_VOID_TAGS_RE.sub("", sanitized)
    sanitized = _REMOVE_EVENT_HANDLER_ATTRS_RE.sub("", sanitized)
    sanitized = _DANGEROUS_SCHEME_QUOTED_RE.sub(r' \1="#"', sanitized)
    sanitized = _DANGEROUS_SCHEME_UNQUOTED_RE.sub(r' \1="#"', sanitized)
    return sanitized
